const GRADE_LEVELS = [
  "PRE_PRIMARY",
  "GRADE_1",
  "GRADE_2",
  "GRADE_3",
  "GRADE_4",
  "GRADE_5",
  "GRADE_6",
  "GRADE_7",
  "GRADE_8",
  "GRADE_9",
  "GRADE_10",
  "GRADE_11",
  "GRADE_12",
  "UNIVERSITY",
  "COLLEGE",
];

const COURSE_LEVELS = ["BEGINNER", "INTERMEDIATE", "ADVANCED"];

module.exports = { GRADE_LEVELS, COURSE_LEVELS };
