module.exports = {
  User: require("./User"),
  Category: require("./Category"),
  Subject: require("./Subject"),
  Course: require("./Course"),
  CourseProposal: require("./CourseProposal"),
  Class: require("./Class"),
  Session: require("./Session"),
  SessionAttendance: require("./SessionAttendance"),
  Enrollment: require("./Enrollment"),
  Payment: require("./Payment"),
  Transaction: require("./Transaction"),
  TeacherEarning: require("./TeacherEarning"),
  Review: require("./Review"),
  ScholarshipCampaign: require("./ScholarshipCampaign"),
  SponsorContribution: require("./SponsorContribution"),
  ScholarshipApplication: require("./ScholarshipApplication"),
  Scholarship: require("./Scholarship"),
  ScholarshipUsage: require("./ScholarshipUsage"),
  VerificationDocument: require("./VerificationDocument"),
  Notification: require("./Notification"),
  Conversation: require("./Conversation"),
  Message: require("./Message"),
  Report: require("./Report"),
  AuditLog: require("./AuditLog"),
};
